# Generated by Django 5.0.3 on 2024-04-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=10)),
                ('birthday', models.DateField()),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
