# Generated by Django 5.0.3 on 2024-04-09 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.IntegerField(default=0)),
                ('shipping', models.IntegerField(default=0)),
                ('grandtotle', models.IntegerField(default=0)),
                ('custom_name', models.CharField(max_length=100)),
                ('custom_mail', models.CharField(max_length=100)),
                ('custom_mobile', models.CharField(max_length=20)),
                ('paytype', models.CharField(max_length=20)),
                ('custom_address', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('uni_price', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('dtotal', models.IntegerField(default=0)),
                ('dorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
            ],
        ),
    ]
